parameters:
    visualm.data.cache.collector_cache.class: 'VisualM\DataExtractBundle\Cache\CollectorCache'
    visualm.data.dictionary_collector.class: 'VisualM\DataExtractBundle\Data\DictionaryCollector'
    visualm.data.data_collector.class: 'VisualM\DataExtractBundle\Data\DataCollector'

services:

    visualm.data.cache.collector_cache:
        class: '%visualm.data.cache.collector_cache.class%'
        arguments:
            - '%kernel.cache_dir%'
            - '%kernel.debug%'
        tags:
            - { name: kernel.cache_clearer }

    visualm.data.dictionary_collector:
        class: '%visualm.data.dictionary_collector.class%'
        arguments:
            - "@annotation_reader"
            - "@doctrine.orm.entity_manager"
            - "@visualm.data.cache.collector_cache"
        tags:
            - { name: kernel.cache_warmer, priority: 0 }

    visualm.data.data_collector:
        class: '%visualm.data.data_collector.class%'
        arguments:
            - "@visualm.data.dictionary_collector"
